(() => {
const $=id=>document.getElementById(id); const editor=$('richEditor'),status=$('editorStatus'); if(!editor)return;
const categories=[...new Set(TEXTS.map(t=>t.category))]; $('edCategory').innerHTML=categories.map(c=>`<option>${c}</option>`).join('');
function ensureCategory(c){if(c&&![...$('edCategory').options].some(o=>o.value===c))$('edCategory').add(new Option(c,c));}
function focusEditor(){editor.focus()}
document.querySelectorAll('#toolbar [data-cmd]').forEach(b=>b.addEventListener('click',()=>{focusEditor();document.execCommand(b.dataset.cmd,false,null)}));
document.querySelectorAll('#toolbar [data-block]').forEach(b=>b.addEventListener('click',()=>{focusEditor();document.execCommand('formatBlock',false,b.dataset.block)}));
$('fontFamily').addEventListener('change',e=>{focusEditor();document.execCommand('fontName',false,e.target.value)}); $('fontSize').addEventListener('change',e=>{focusEditor();document.execCommand('fontSize',false,e.target.value)});
$('addLink').onclick=()=>{const u=prompt('Adresse du lien :','https://');if(u){focusEditor();document.execCommand('createLink',false,u)}}; $('addRule').onclick=()=>{focusEditor();document.execCommand('insertHorizontalRule',false,null)}; $('clearFormat').onclick=()=>{focusEditor();document.execCommand('removeFormat',false,null)};
function getArticle(){return{id:Date.now().toString(),title:$('edTitle').value.trim()||'Sans titre',date:$('edDate').value,category:$('edCategory').value,subtitle:$('edSubtitle').value.trim(),ambience:$('edAmbience')?.value||'default',html:editor.innerHTML}}
function slugify(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'texte'}
function setStatus(s){status.textContent=s;setTimeout(()=>{if(status.textContent===s)status.textContent=''},5000)}
function escapeHTML(s){return(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function ambienceName(v){return v==='none'?'silence':v==='custom'?'ambiance propre':'bibliothèque'}
$('previewBtn').onclick=()=>{const a=getArticle();$('previewTitle').textContent=a.title;$('previewSubtitle').textContent=a.subtitle;$('previewMeta').textContent=`${a.category}${a.date?' · '+new Date(a.date+'T12:00:00').toLocaleDateString('fr-FR'):''} · Ambiance : ${ambienceName(a.ambience)}`;$('previewArticle').innerHTML=a.html;$('previewModal').style.display='block';document.body.style.overflow='hidden'}; $('previewClose').onclick=()=>{$('previewModal').style.display='none';document.body.style.overflow=''};
function drafts(){try{return JSON.parse(localStorage.getItem('pitou-drafts')||'[]')}catch{return[]}}
function writeDrafts(d){localStorage.setItem('pitou-drafts',JSON.stringify(d));renderDrafts()}
function published(){try{return JSON.parse(localStorage.getItem('pitou-published')||'[]')}catch{return[]}}
function savePublished(d){localStorage.setItem('pitou-published',JSON.stringify(d));renderPublished()}
function stripSubtitle(html){const d=document.createElement('div');d.innerHTML=html;const s=d.querySelector('.subtitle');if(s)s.remove();return d.innerHTML}
function loadArticle(a,slug=''){$('edOriginalSlug').value=slug||a.slug||'';$('edTitle').value=a.title||'';$('edDate').value=a.date||'';ensureCategory(a.category);$('edCategory').value=a.category||categories[0]||'';$('edSubtitle').value=a.subtitle||'';if($('edAmbience'))$('edAmbience').value=a.ambience||'default';editor.innerHTML=stripSubtitle(a.html||'<p></p>');window.scrollTo({top:0,behavior:'smooth'});setStatus('Texte chargé dans l’éditeur.')}
$('saveDraftBtn').onclick=()=>{const a=getArticle(),d=drafts(),i=d.findIndex(x=>x.title===a.title);if(i>=0)a.id=d[i].id,d[i]=a;else d.unshift(a);writeDrafts(d.slice(0,50));setStatus('Brouillon sauvegardé dans ce navigateur.')};
function renderDrafts(){const d=drafts();$('draftList').innerHTML=d.length?d.map(x=>`<div class="draft-item"><button data-id="${x.id}">${escapeHTML(x.title)}</button><small>${escapeHTML(x.category)}${x.date?' · '+x.date:''}</small></div>`).join(''):'<small>Aucun brouillon.</small>';$('draftList').querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=d.find(x=>x.id===b.dataset.id);if(a)loadArticle(a,'')})}
function renderPublished(){const d=published();$('publishedList').innerHTML=d.length?d.map(x=>`<div class="draft-item"><button class="published-open" data-slug="${escapeHTML(x.slug)}">${escapeHTML(x.title)}</button><small>${escapeHTML(x.category)}${x.date?' · '+x.date:''} · ${ambienceName(x.ambience||'default')}</small><button class="published-delete" data-delete="${escapeHTML(x.slug)}" style="color:#b98f79;font-size:.78rem">Supprimer</button></div>`).join(''):'<small>Aucun texte publié depuis cet appareil.</small>';$('publishedList').querySelectorAll('.published-open').forEach(b=>b.onclick=()=>{const a=d.find(x=>x.slug===b.dataset.slug);if(a)loadArticle(a,a.slug)});$('publishedList').querySelectorAll('.published-delete').forEach(b=>b.onclick=()=>{const a=d.find(x=>x.slug===b.dataset.delete);if(!a)return;if(confirm(`Supprimer « ${a.title} » des Carnets sur ce navigateur ?`)){savePublished(d.filter(x=>x.slug!==a.slug));if($('edOriginalSlug').value===a.slug)newPage(false);setStatus('Texte supprimé de la bibliothèque locale.')}})}
function newPage(ask=true){if(ask&&!confirm('Vider l’éditeur pour commencer un nouveau texte ?'))return;$('edOriginalSlug').value='';$('edTitle').value='';$('edDate').value='';$('edSubtitle').value='';if($('edAmbience'))$('edAmbience').value='default';editor.innerHTML='<p></p>';setStatus('Nouvelle page.')}
$('newBtn').onclick=()=>newPage(true);
$('exportBtn').onclick=()=>{const a=getArticle(),slug=slugify(a.title);const file=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${escapeHTML(a.title)}</title></head><body><article class="article" data-title="${escapeHTML(a.title)}" data-date="${escapeHTML(a.date)}" data-category="${escapeHTML(a.category)}" data-ambience="${escapeHTML(a.ambience)}">${a.subtitle?`<p class="subtitle"><em>${escapeHTML(a.subtitle)}</em></p>`:''}${a.html}</article></body></html>`;const blob=new Blob([file],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=slug+'.html';link.click();URL.revokeObjectURL(url);setStatus('Article exporté.')};
editor.addEventListener('paste',()=>setTimeout(()=>setStatus('Texte collé. Vérifie l’aperçu : Word peut importer quelques styles inutiles.'),50));
function stripText(html){const d=document.createElement('div');d.innerHTML=html;return(d.textContent||'').replace(/\s+/g,' ').trim()} function estimateMinutes(html){return Math.max(1,Math.ceil(stripText(html).split(/\s+/).filter(Boolean).length/220))}
$('publishBtn').onclick=()=>{const a=getArticle();if(!$('edTitle').value.trim()){setStatus('Ajoute un titre avant de publier.');return}const plain=stripText(a.html);if(!plain){setStatus('Le texte est vide.');return}const oldSlug=$('edOriginalSlug').value,newSlug=slugify(a.title),item={slug:newSlug,title:a.title,date:a.date||'',category:a.category,subtitle:a.subtitle||'',ambience:a.ambience,minutes:estimateMinutes(a.html),excerpt:plain.slice(0,220)+(plain.length>220?'…':''),html:(a.subtitle?`<p class="subtitle"><em>${escapeHTML(a.subtitle)}</em></p>`:'')+a.html,local:true};let d=published();let i=oldSlug?d.findIndex(x=>x.slug===oldSlug):d.findIndex(x=>x.slug===newSlug);if(i>=0){if(!confirm('Mettre à jour ce texte publié ?'))return;d[i]=item}else{const clash=d.findIndex(x=>x.slug===newSlug);if(clash>=0){if(!confirm('Un texte portant ce titre existe déjà. Le remplacer ?'))return;d[clash]=item}else d.unshift(item)}savePublished(d);$('edOriginalSlug').value=newSlug;setStatus('Texte publié / mis à jour dans les Carnets de ce navigateur.')};
$('exportLibraryBtn').onclick=()=>{const payload={format:'carnets-de-pitou-library-v1',exported_at:new Date().toISOString(),published:published(),drafts:drafts()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='carnets-de-pitou-sauvegarde.json';a.click();URL.revokeObjectURL(url);setStatus('Sauvegarde de la bibliothèque exportée.')};
$('importLibraryInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.format!=='carnets-de-pitou-library-v1')throw new Error();if(!confirm('Restaurer cette sauvegarde ?'))return;savePublished(Array.isArray(p.published)?p.published:[]);writeDrafts(Array.isArray(p.drafts)?p.drafts:[]);setStatus('Sauvegarde restaurée.')}catch{setStatus('Fichier de sauvegarde invalide.')}});
renderDrafts();renderPublished();
})();