(()=>{
const OWNER='Carnet-de-Pitou',REPO='carnets-de-pitou',BRANCH='main',MANIFEST='library-items.js';
const btn=document.getElementById('publishBtn');if(!btn)return;const actions=btn.parentElement,status=document.getElementById('editorStatus');
function say(s){if(status)status.textContent=s}function esc(s){return(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function slugify(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'texte'}function plain(h){const d=document.createElement('div');d.innerHTML=h;return(d.textContent||'').replace(/\s+/g,' ').trim()}
function currentItem(){const title=(document.getElementById('edTitle')?.value||'').trim(),raw=document.getElementById('richEditor')?.innerHTML||'',text=plain(raw),subtitle=(document.getElementById('edSubtitle')?.value||'').trim(),original=document.getElementById('edOriginalSlug')?.value||'',series=document.getElementById('edSeries')?.value||'';return{slug:original||slugify(title),title,date:document.getElementById('edDate')?.value||'',category:document.getElementById('edCategory')?.value||'',subtitle,ambience:document.getElementById('edAmbience')?.value||'default',...(series?{series}:{}),minutes:Math.max(1,Math.ceil(text.split(/\s+/).filter(Boolean).length/220)),excerpt:text.slice(0,220)+(text.length>220?'…':''),html:(subtitle?`<p class="subtitle"><em>${esc(subtitle)}</em></p>`:'')+raw,local:false}}
function token(){return sessionStorage.getItem('pitou-github-token')||''}function connect(){const t=prompt('Colle ton jeton GitHub dédié aux Carnets. Il restera uniquement dans cet onglet.');if(!t)return false;sessionStorage.setItem('pitou-github-token',t.trim());say('GitHub connecté.');return true}async function api(url,o={}){const r=await fetch(url,{...o,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(token()?{Authorization:'Bearer '+token()}:{}),...(o.headers||{})}});if(!r.ok){let m='Erreur GitHub '+r.status;try{const j=await r.json();if(j.message)m+=' : '+j.message}catch{}throw new Error(m)}return r.json()}
function b64(s){const bytes=new TextEncoder().encode(s);let x='';for(const b of bytes)x+=String.fromCharCode(b);return btoa(x)}function unb64(s){const x=atob((s||'').replace(/\s/g,''));return new TextDecoder().decode(Uint8Array.from(x,c=>c.charCodeAt(0)))}
async function getFile(path){const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}?ref=${BRANCH}&_=${Date.now()}`,{headers:{Accept:'application/vnd.github+json',...(token()?{Authorization:'Bearer '+token()}:{})}});if(r.status===404)return null;if(!r.ok)throw new Error('Erreur GitHub '+r.status);const j=await r.json();return{sha:j.sha,text:unb64(j.content||'')}}
async function put(path,text,message,sha){const body={message,content:b64(text),branch:BRANCH,...(sha?{sha}:{})};return api(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function itemScript(item){return 'window.PITOU_LIBRARY_ITEM = '+JSON.stringify(item)+';\n'}function manifestScript(slugs){return 'window.PITOU_LIBRARY_ITEM_SLUGS = '+JSON.stringify(slugs)+';\n'}
async function readManifest(){const f=await getFile(MANIFEST);if(!f)return{sha:null,slugs:[]};const m=f.text.match(/=\s*(\[[\s\S]*\])\s*;?\s*$/);if(!m)throw new Error('Index des nouveaux textes illisible');return{sha:f.sha,slugs:JSON.parse(m[1])}}
async function publish(){const item=currentItem();if(!item.title){say('Ajoute un titre avant de mettre en ligne.');return}if(!plain(item.html)){say('Le texte est vide.');return}btn.click();if(!token()&&!connect())return;const direct=document.getElementById('publishDirectBtn');if(direct)direct.disabled=true;try{say('Publication indépendante de « '+item.title+' »…');const path='texts/'+item.slug+'.js',old=await getFile(path);await put(path,itemScript(item),'Publie le texte : '+item.title,old?.sha);const mf=await readManifest(),slugs=[...new Set([...mf.slugs,item.slug])];await put(MANIFEST,manifestScript(slugs),'Met à jour l’index des textes',mf.sha);const check=await getFile(path);if(!check||!check.text.includes(JSON.stringify(item.slug)))throw new Error('ALERTE : vérification du texte impossible.');localStorage.setItem('pitou-published','[]');say('Publié et vérifié : « '+item.title+' ». Le texte est maintenant stocké indépendamment.');setTimeout(()=>location.reload(),3500)}catch(e){say(e.message+' — aucune donnée locale n’a été supprimée.')}finally{if(direct)direct.disabled=false}}
let direct=document.getElementById('publishDirectBtn');if(!direct){direct=document.createElement('button');direct.type='button';direct.id='publishDirectBtn';direct.className='admin-primary';direct.textContent='Mettre en ligne sur le site';actions.insertBefore(direct,btn.nextSibling)}direct.onclick=publish;let c=document.getElementById('githubConnectBtn');if(!c){c=document.createElement('button');c.type='button';c.id='githubConnectBtn';c.textContent='Connexion GitHub';actions.appendChild(c)}c.onclick=connect;window.publishPitouToGitHub=publish;
})();