(()=>{
const OWNER='Carnet-de-Pitou',REPO='carnets-de-pitou',PATH='library.js',BRANCH='main';
const btn=document.getElementById('publishBtn');if(!btn)return;
const actions=btn.parentElement,status=document.getElementById('editorStatus');
function say(s){if(status)status.textContent=s}
function esc(s){return(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function slugify(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'texte'}
function plain(html){const d=document.createElement('div');d.innerHTML=html;return(d.textContent||'').replace(/\s+/g,' ').trim()}
function currentItem(){const title=(document.getElementById('edTitle')?.value||'').trim(),editor=document.getElementById('richEditor'),raw=editor?.innerHTML||'',text=plain(raw),subtitle=(document.getElementById('edSubtitle')?.value||'').trim(),original=document.getElementById('edOriginalSlug')?.value||'',series=document.getElementById('edSeries')?.value||'';return{slug:original||slugify(title),title,date:document.getElementById('edDate')?.value||'',category:document.getElementById('edCategory')?.value||'',subtitle,ambience:document.getElementById('edAmbience')?.value||'default',...(series?{series}:{}),minutes:Math.max(1,Math.ceil(text.split(/\s+/).filter(Boolean).length/220)),excerpt:text.slice(0,220)+(text.length>220?'…':''),html:(subtitle?`<p class="subtitle"><em>${esc(subtitle)}</em></p>`:'')+raw,local:false}}
function validList(list){if(!Array.isArray(list))throw new Error('Bibliothèque GitHub invalide');const slugs=list.filter(Boolean).map(t=>t.slug).filter(Boolean);const dup=slugs.find((s,i)=>slugs.indexOf(s)!==i);if(dup)throw new Error('Sécurité : doublon détecté ('+dup+'). Publication annulée.');return slugs}
function mergeInto(base,extra){const map=new Map();(Array.isArray(base)?base:[]).forEach(t=>t&&t.slug&&map.set(t.slug,{...t,local:false}));if(extra&&extra.slug)map.set(extra.slug,{...extra,local:false});return[...map.values()]}
function content(list){return 'window.PITOU_PUBLIC_LIBRARY = '+JSON.stringify(list)+';\n'}
function b64unicode(str){const bytes=new TextEncoder().encode(str);let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin)}
function decodeGithubText(b64){const bin=atob((b64||'').replace(/\s/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function parseLibrary(source){const marker='window.PITOU_PUBLIC_LIBRARY = ';const i=source.indexOf(marker);if(i<0)throw new Error('Bibliothèque GitHub illisible');let raw=source.slice(i+marker.length).trim();if(raw.endsWith(';'))raw=raw.slice(0,-1);const list=JSON.parse(raw);validList(list);return list}
function token(){return sessionStorage.getItem('pitou-github-token')||''}
function connect(){const t=prompt('Colle ton jeton GitHub dédié aux Carnets. Il restera uniquement dans cet onglet.');if(!t)return false;sessionStorage.setItem('pitou-github-token',t.trim());say('GitHub connecté.');return true}
async function api(url,options={}){const t=token();const r=await fetch(url,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(t?{Authorization:'Bearer '+t}:{}),...(options.headers||{})}});if(!r.ok){let msg='Erreur GitHub '+r.status;try{const j=await r.json();if(j.message)msg+=' : '+j.message}catch{}throw new Error(msg)}return r.json()}
async function readRemote(){const current=await api(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}?ref=${BRANCH}&_=${Date.now()}`);let encoded=current.content||'';if(!encoded.trim()&&current.sha){const blob=await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/blobs/${current.sha}?_=${Date.now()}`);encoded=blob.content||''}if(!encoded.trim())throw new Error('Bibliothèque GitHub illisible : contenu distant introuvable');return{current,list:parseLibrary(decodeGithubText(encoded))}}
async function writeLargeFile(text,message){const ref=await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/ref/heads/${BRANCH}?_=${Date.now()}`);const parent=ref.object.sha;const parentCommit=await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/commits/${parent}`);const blob=await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/blobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:b64unicode(text),encoding:'base64'})});const tree=await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/trees`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:parentCommit.tree.sha,tree:[{path:PATH,mode:'100644',type:'blob',sha:blob.sha}]})});const commit=await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/commits`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,tree:tree.sha,parents:[parent]})});await api(`https://api.github.com/repos/${OWNER}/${REPO}/git/refs/heads/${BRANCH}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:commit.sha,force:false})});return commit.sha}
function stamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}_${p(d.getHours())}-${p(d.getMinutes())}-${p(d.getSeconds())}`}
function backupPayload(list,reason='manuel'){let drafts=[];try{drafts=JSON.parse(localStorage.getItem('pitou-drafts')||'[]')}catch{}return{format:'carnets-de-pitou-complet-v2',created_at:new Date().toISOString(),reason,published:list,drafts:Array.isArray(drafts)?drafts:[]}}
function downloadBackup(list,reason='manuel'){const blob=new Blob([JSON.stringify(backupPayload(list,reason),null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`carnets-de-pitou-sauvegarde-${stamp()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function manualBackup(){if(!token()&&!connect())return;try{const remote=await readRemote();downloadBackup(remote.list,'manuel');say('Sauvegarde complète téléchargée : '+remote.list.length+' texte(s).')}catch(e){say(e.message)}}
async function publishGitHub(){const item=currentItem();if(!item.title){say('Ajoute un titre avant de mettre en ligne.');return}if(!plain(item.html)){say('Le texte est vide.');return}btn.click();if(!token()&&!connect())return;const direct=document.getElementById('publishDirectBtn');if(direct)direct.disabled=true;say('Publication sécurisée de « '+item.title+' »…');try{const before=await readRemote();downloadBackup(before.list,'automatique-avant-publication');const beforeSlugs=validList(before.list),beforeSet=new Set(beforeSlugs),existed=beforeSet.has(item.slug),finalLibrary=mergeInto(before.list,item),expected=before.list.length+(existed?0:1);validList(finalLibrary);if(finalLibrary.length!==expected)throw new Error('Sécurité : nombre de textes inattendu. Publication annulée.');if([...beforeSet].some(s=>!finalLibrary.some(t=>t.slug===s)))throw new Error('Sécurité : un ancien texte disparaîtrait. Publication annulée.');await writeLargeFile(content(finalLibrary),'Publication depuis l’éditeur des Carnets : '+item.title);const after=await readRemote(),afterSet=new Set(validList(after.list)),missing=beforeSlugs.filter(s=>!afterSet.has(s)),saved=after.list.find(t=>t&&t.slug===item.slug);if(missing.length)throw new Error('ALERTE : '+missing.length+' ancien(s) texte(s) manquent après publication.');if(!saved)throw new Error('ALERTE : le texte publié est absent de GitHub.');if(after.list.length!==expected)throw new Error('ALERTE : nombre de textes incohérent après publication.');window.PITOU_PUBLIC_LIBRARY=after.list;localStorage.setItem('pitou-published','[]');say('Publié et vérifié : « '+item.title+' ». '+after.list.length+' texte(s) dans la bibliothèque courante.');setTimeout(()=>location.reload(),4000)}catch(e){say(e.message+' — aucune donnée locale n’a été supprimée.');if(e.message.includes('401')||e.message.includes('403'))sessionStorage.removeItem('pitou-github-token')}finally{if(direct)direct.disabled=false}}
let direct=document.getElementById('publishDirectBtn');if(!direct){direct=document.createElement('button');direct.type='button';direct.id='publishDirectBtn';direct.className='admin-primary';direct.textContent='Mettre en ligne sur le site';actions.insertBefore(direct,btn.nextSibling)}direct.onclick=publishGitHub;let backup=document.getElementById('fullBackupBtn');if(!backup){backup=document.createElement('button');backup.type='button';backup.id='fullBackupBtn';backup.textContent='Sauvegarder tous mes Carnets';actions.appendChild(backup)}backup.onclick=manualBackup;let connectBtn=document.getElementById('githubConnectBtn');if(!connectBtn){connectBtn=document.createElement('button');connectBtn.type='button';connectBtn.id='githubConnectBtn';connectBtn.textContent='Connexion GitHub';actions.appendChild(connectBtn)}connectBtn.onclick=connect;window.publishPitouToGitHub=publishGitHub;
})();